BUILD_MODE ?= cuda

GPU := H100
ARCH := SM90
SRC := linear_bwd_fused.cu

ifeq ($(BUILD_MODE),torch)
	OUT := _linear_bwd_fused$(shell python3 -c "import sysconfig; print(sysconfig.get_config_var('EXT_SUFFIX'))")
	CMD :=
	CONFIG := pytorch
	NVCCFLAGS := -DTORCH_COMPILE -UTORCH_EXTENSION_NAME -DTORCH_EXTENSION_NAME=_linear_bwd_fused
else ifeq ($(BUILD_MODE),cuda)
	OUT := linear_bwd_fused.out
	CMD := ./linear_bwd_fused.out
	CONFIG := standalone
else
	$(error Invalid BUILD_MODE. Use 'torch' or 'cuda')
endif

include ../../common.mk
